"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var VALUES;
(function (VALUES) {
    VALUES[VALUES["ZERO"] = 0] = "ZERO";
    VALUES[VALUES["ONE"] = 1] = "ONE";
    VALUES[VALUES["TWO"] = 2] = "TWO";
    VALUES[VALUES["THREE"] = 3] = "THREE";
    VALUES[VALUES["FOUR"] = 4] = "FOUR";
    VALUES[VALUES["FIVE"] = 5] = "FIVE";
    VALUES[VALUES["SIX"] = 6] = "SIX";
    VALUES[VALUES["SEVEN"] = 7] = "SEVEN";
    VALUES[VALUES["EIGHT"] = 8] = "EIGHT";
    VALUES[VALUES["NINE"] = 9] = "NINE";
    VALUES[VALUES["REVERSE"] = 10] = "REVERSE";
    VALUES[VALUES["SKIP"] = 11] = "SKIP";
    VALUES[VALUES["DrawTwo"] = 12] = "DrawTwo";
    VALUES[VALUES["WILD"] = 13] = "WILD";
    VALUES[VALUES["WildDrawFour"] = 14] = "WildDrawFour";
})(VALUES || (VALUES = {}));
exports.VALUES = VALUES;
;
